steps:
  - name: gcr.io/cloud-builders/docker
    args: [build, '-t', 'europe-west1-docker.pkg.dev/${PROJECT_ID}/production-build/build:latest', '.']
images:
  - 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/production-build/build:latest'
options: 
  logging: CLOUD_LOGGING_ONLY